dist: xenial
language: node_js
node_js:
  - 10.13.0
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
install: true
script:
  - yarn
  - yarn test
  - yarn run build
  - yarn cypress:install && yarn e2e:ci
